- resources/assets/css/_forms.css
https://app.clickup.com/t/1f3a46a
PR based on old laravel-ui repo PR (https://github.com/ArkEcosystem/laravel-ui/pull/671)
> refactor: update focused select border

- README.md
https://app.clickup.com/t/1nf0p95
> fix: repository banner

- src/UserInterface/Eloquent/Concerns/HasSchemalessAttributes.php
This is for the HasSchemalessAttribute trait that was updated in the last release
Related to https://github.com/ArkEcosystem/nodem/pull/275
> refactor: update phpstan property type

- resources/assets/css/_document.css
https://app.clickup.com/t/1kvtkbk
> refactor: remove documentation accordion table margin

- resources/views/navbar/profile.blade.php
https://app.clickup.com/t/1mjky61
> refactor: navbar allow profile menu icons & divider

- resources/views/navbar.blade.php
- resources/views/navbar/content.blade.php
- resources/views/navbar/hamburger.blade.php
- resources/views/navbar/items/desktop.blade.php
- resources/views/navbar/items/mobile.blade.php
https://app.clickup.com/t/1mjknak
relates to https://github.com/PayvoHQ/payvo.com/pull/71
**Note: updates the margin/padding of the separator so may need to adjust margin on logged-in elements (e.g. notifications button) on other projects that use custom**
-   [ ] …
> refactor: navbar allow extra navigation items

- resources/views/sidebar-link.blade.php
> refactor: icon alignment for sidebar-link component

- resources/assets/css/_general.css
h3 and h4 should be 18px on sm devices, not 20px
related to https://app.clickup.com/t/1my0df6 ? - it was noticed for this task at least
> refactor: update heading sizes

- config/livewire.php
- src/Providers/FoundationServiceProvider.php
- src/Providers/UserInterfaceServiceProvider.php
- tests/Fortify/Components/VerifyEmailTest.php
- usage/ui.md
> chore: add livewire config publisher

- src/Fortify/Rules/Concerns/BaseRule.php
- src/Fortify/Rules/Concerns/ReservedUsername.php
- src/Fortify/Rules/Username.php
Related to https://github.com/PayvoHQ/payvo.com/pull/133
> refactor: add typehints for ReservedUsername rule

- src/Fortify/Components/Concerns/InteractsWithUser.php
https://app.clickup.com/t/1rb0evp
This PR adds a `@property` doc-block to `InteractsWithUser` trait to help static analysis tool to infer the correct type.
> refactor: add php doc-block to InteractsWithUser trait

- phpstan.neon
https://app.clickup.com/t/1t1u7u1
> chore: improve phpstan ignored errors

- src/UserInterface/Support/Enums/FlashType.php
- src/UserInterface/helpers.php
https://app.clickup.com/t/1td7364
This PR adds an `alert()` helper to flash a message on a session.
> refactor: add "alert()" helper to flash a message on a session

- phpstan.neon
https://app.clickup.com/t/1td722k
This PR adds "Dynamic call to static method" to phpstan's ignored errors list.
> refactor: add `dynamic call to static method` to phpstan ignored errors

- resources/assets/css/_components.css
https://app.clickup.com/t/1ravkpq
> refactor: disabled icon tile color

- README.md
This package contains a lot of frontend components, but no frontend views itself. So when you need to work on it, you rely on the frontend from another  project. Usually this can be done by having composer symlink this package, but in this case there is a second step required to ensure you can run `npm run watch`,  `npm run prod` etc. 
This PR adds instructions on how you can achieve that.
-   [ ] I regenerated the `icons.html` file and checked if my newly added icon is …
> docs: added instructions on how to test locally

- resources/views/profile/logout-other-browser-sessions-form.blade.php
https://app.clickup.com/t/1tyew2g
> fix: truncate ipv6 address in session settings component

- phpstan.neon
https://app.clickup.com/t/1v0jvwc
> chore: add "Access to an undefined property Spatie\Activitylog\Models\Activity" to phpstan ignored errors

- resources/assets/css/_forms.css
- resources/views/newsletter/footer-subscription-form.blade.php
https://app.clickup.com/t/1uv22gt
> refactor: allow input forced light mode & use in footer

- config/share.php
- src/Providers/UserInterfaceServiceProvider.php
- src/UserInterface/Support/Share.php
- tests/UserInterface/Support/ShareTest.php
- tests/__snapshots__/ShareTest__it_shares_url_with_(facebook)__1.txt
- tests/__snapshots__/ShareTest__it_shares_url_with_(reddit)__1.txt
- tests/__snapshots__/ShareTest__it_shares_url_with_(twitter)__1.txt
- usage/ui.md
https://app.clickup.com/t/1v6fbdu
This PR adds the social share link functionality.
see https://github.com/ArkEcosystem/marketsquare.io/pull/2453
-   [x] I added an explanation on how to use the component to the readme _(if necessary)_
-   [x] Documentation _(if necessary)_
-   [x] Tests _(if necessary)_
> feat: social share link

- src/UserInterface/Support/Share.php
- src/UserInterface/helpers.php
- tests/UserInterface/Support/ShareTest.php
- tests/__snapshots__/ShareTest__it_share_url_facebook__1.txt
https://app.clickup.com/t/1v6fbdu
> refactor: use static methods in Share class

- resources/views/external-link-confirm.blade.php
https://app.clickup.com/t/1mucv54
Adds the stopPropagation handler to prevent observers added by the Twitter script
-   [x] I regenerated the `icons.html` file and checked if my newly added icon is shown correctly _(if necessary)_
> fix: twitter links opens in new tab

- resources/views/profile/delete-user-form.blade.php
Change the delete project icon size so it's fixed at 240px at all breakpoints.
> fix: "delete project" modal image size

- resources/views/pages/includes/header.blade.php
https://app.clickup.com/t/1muegnq
Semi-related to https://github.com/ArkEcosystem/marketsquare.io/pull/2422
> fix: page header description offset

- resources/views/js-modal.blade.php
https://app.clickup.com/t/1vx6dk8
> refactor: fix modal title tag

- resources/views/notification-icon.blade.php
- src/Hermes/Enums/NotificationTypeEnum.php
We need this change so we can make these video notifications:
https://app.clickup.com/t/1vx6x29
> refactor: allow video/play icon in notifications

- resources/lang/en/generic.php
Add key for `an` so it can be used for the footer on payvo
> chore: add "an" language key

- resources/views/notification-icon.blade.php
https://app.clickup.com/t/1w8pk69
This is only testable as soon as this PR is merged: https://github.com/ArkEcosystem/marketsquare.io/pull/2492 
In MSQ:
- Have your user to follow Ark hub.
- In Nova: make sure Ark platform has a SVG as photo (it has it already if you're using the dev Playbook).
- In Nova: Add a Video to the Arp platform.
- Check the notifications for the user.
-   [ ] I regenerated the `icons.html` file and checked if my newly added icon is shown …
> fix: platform svg is not showing in notifications

- resources/views/inputs/upload-image-collection.blade.php
Relates to https://app.clickup.com/t/1qvbefd
required for https://github.com/ArkEcosystem/marketsquare.io/pull/2515
> refactor: handle compressorjs package update to 1.1.1

- resources/assets/js/chart.js
https://app.clickup.com/t/1wtxg92
> fix: chart grid line colour

- resources/assets/css/_buttons.css
Related to: https://app.clickup.com/t/1vx6d5h
Dependant of https://github.com/ArkEcosystem/marketsquare.io/pull/2504
Add the button-tertiary variant:
Regular:
Hover:
Disabled:
-   [ ] Ready to be …
> feat: add button-tertiary classes

- resources/views/navbar/items/dropdown-item.blade.php
Required by https://github.com/PayvoHQ/payvo.com/pull/170
> refactor: transition navbar dropdown item text

- README.md
https://app.clickup.com/t/1wzrkbe
This PR improves the README.md file by adding scripts to help developers linking current projects to `laravel-foundation` during development/test process and section on how to use them.
-   [ ] …
> chore: add link/unlink:foundation scripts into README.md

- resources/assets/css/_slider.css
https://app.clickup.com/t/1wu0vdz
Dark mode dots and separator for slider.
On the MSQ homepage you can find these elements in the `Around the Square` section.
> refactor: dark mode dots and separator

- resources/views/pages/includes/header.blade.php
https://app.clickup.com/t/1wu10jd
This PR simply adds a dark mode background for the header on all policy pages.
> feat: add dark mode to policy page headers

- resources/assets/css/_forms.css
- resources/views/components/component-heading.blade.php
- resources/views/components/form-wrapper.blade.php
- resources/views/inputs/includes/input-error-tooltip.blade.php
- resources/views/inputs/input-with-prefix.blade.php
https://app.clickup.com/t/1wu0ymk
### To test:
1. Merge the changes here to msq, recompile and check login and register forms
2. Consider different states like error messages, etc
3. check mobile version
-   [ x] I checked my UI changes for any responsiveness issues
-   [x] I regenerated the `icons.html` file and checked if my newly added icon is shown correctly _(if necessary)_
-   [x] I added an explanation on how to use the component to the readme _(if necessary)_
-   [ ] Tests _(if …
> feat: login/register form dark mode

- resources/assets/css/_forms.css
- resources/views/pages/contact.blade.php
- resources/views/social-square.blade.php
https://app.clickup.com/t/1wu0ypb
Required by https://github.com/ArkEcosystem/marketsquare.io/pull/2535
> refactor: contact dark mode

- resources/assets/css/_alerts.css
- resources/assets/css/_forms.css
- resources/views/profile/logout-other-browser-sessions-form.blade.php
- resources/views/profile/two-factor-authentication-form.blade.php
- resources/views/secondary-menu.blade.php
- resources/views/sidebar-link.blade.php
https://app.clickup.com/t/1wu0yqk
Adjustments related to the user setting page on msq.
To test merge this on the msq pr, recompile and check views as usual.
> refactor: user settings dark mode

- resources/assets/css/_forms.css
- resources/views/inputs/checkbox.blade.php
https://app.clickup.com/t/1wu12gr
Adjust the text color and border so it matchs the design:
> refactor: adjust checkbox dark mode styling

- resources/views/components/password-rules.blade.php
https://app.clickup.com/t/1xb48xc
Use foundation in a MSQ and don't forget to compile assets.
Go to `register` to see the changes (in dark mode)
> refactor: dark mode support password requirements

- resources/assets/css/_buttons.css
- resources/assets/css/_document.css
- resources/views/divider.blade.php
- resources/views/shapes/line.blade.php
- resources/views/shapes/square.blade.php
https://app.clickup.com/t/1xb5djd
Required by https://github.com/ArkEcosystem/marketsquare.io/pull/2553
Separate to above:
https://app.clickup.com/t/1xgphqu
https://app.clickup.com/t/1xgt56z
-   [x] …
> refactor: dark mode cancel button, divider, placeholders, etc

- resources/assets/css/_forms.css
- resources/views/components/modals/2fa-recovery-codes.blade.php
https://app.clickup.com/t/1z4e5wt
> refactor: recovery codes dark mode

- resources/views/profile/two-factor-authentication-form.blade.php
https://app.clickup.com/t/11m8bg5
> refactor: small text for 2fa secret

- resources/views/components/modals/password-confirmation.blade.php
- resources/views/navbar/items/dropdown-item.blade.php
- resources/views/profile/two-factor-authentication-form.blade.php
https://app.clickup.com/t/1zfucf9
> refactor: replace @svg with <x-ark-icon/>

- resources/views/navbar/content.blade.php
https://app.clickup.com/t/1xx3tb2
Updates the "sign up" button color on dark mode to match the design
**Note:** The ticket also mentions a discrepancy in the "sign in" button but it is currently according to the design and the screenshot on the ticket so not sure if I am missing something.
**To test:** Merge on msq, recompile, profit
-   [ ] I added an …
> refactor: update login button color/hover on dark mode

- resources/views/components/manage-notifications.blade.php
- resources/views/notification-icon.blade.php
Dependant of https://github.com/ArkEcosystem/marketsquare.io/pull/2595
- Fixes an issue with the border of the icon on dark mode:
- Fixed empty state on notifications page
before:
after:
-   [ ] Ready …
> refactor: notifications dark mode tweaks

- resources/views/navbar/profile.blade.php
https://app.clickup.com/t/1znfp2u
* Log in to MSQ
* set `DARK_MODE_ENABLED=false`
* The user-menu should open and the dark mode toggle-switch should not be visible
* set `DARK_MODE_ENABLED=true`
* The user-menu should open and the dark mode toggle-switch should be visible and working
-   [x] I added an explanation on how to use the component to the readme …
> fix: user menu crash when DARK_MODE_ENABLED was false

- resources/tailwind.config.js
- resources/views/navbar/profile.blade.php
https://app.clickup.com/t/1z9wt5a
> refactor: navbar dropdown width when showing dark mode option

- resources/views/navbar-notifications.blade.php
https://app.clickup.com/t/21zvkbf
- Log into MSQ
- Delete all notifications
- refresh and click the notification dropdown in the navbar.
> fix: notification placeholder icon in navbar dropdown

- resources/views/inputs/input-with-suffix.blade.php
Dependant of https://github.com/ArkEcosystem/marketsquare.io/pull/2603
Updates the input suffix background color in both light and dark versions (see the @ark.io suffix)
Before:
After
-   [X] I provided a screenshot of my changes to the component _(if applicable)_
-   [ ] Ready to …
> refactor: update input suffix color

- resources/views/inputs/upload-image-collection.blade.php
https://app.clickup.com/t/22wbjv2
This change is needed for one part of the above task.
> fix: dark borders for image thumbnails

- resources/views/scripts/dark-theme-script.blade.php
https://app.clickup.com/t/22wcxe9
> refactor: dark mode emit livewire event

- resources/views/pagination.blade.php
> fix: use magnifying-glass icon for pagination search

- src/UserInterface/helpers.php
https://app.clickup.com/t/237t3qb
> fix: update alert component to fallback to "circle.info" icon

- resources/views/inputs/includes/markdown/image-modal.blade.php
https://app.clickup.com/t/237ud24
- fix "upload cloud" icon reference
- fix closing tag
> fix: icon reference + closing tag

- resources/views/navbar/items/dropdown-item.blade.php
> fix: navbar dropdown icon height

- resources/views/navbar/items/dropdown-item.blade.php
> fix: external icon on nav-item

- rector.php
https://app.clickup.com/t/237xvaz
> refactor: make rector skip Livewire components and Nova dir

- config/ui.php
https://app.clickup.com/t/1v8ev05
> chore: set dark mode config default to false

- resources/views/secondary-menu.blade.php
https://app.clickup.com/t/1v8f7uc
Required by https://github.com/ArkEcosystem/deployer.io/pull/999
> refactor: add secondary menu customisation

- examples/ui.md
- resources/assets/js/dropdown.js
- resources/views/dropdown.blade.php
https://app.clickup.com/t/237th01
Required by https://github.com/ArkEcosystem/deployer.io/pull/1008
> refactor: dropdown with placement property

- resources/lang/en/pages.php
- resources/lang/en/urls.php
- resources/views/footer-social.blade.php
- resources/views/pages/contact.blade.php
- usage/ui.md
https://app.clickup.com/t/23ryf5x
Required by:
- https://github.com/ArkEcosystem/ark.dev/pull/226
- https://github.com/ArkEcosystem/ark.io/pull/1035
> refactor: remove discord

- resources/views/pages/includes/layout-content.blade.php
- src/Providers/UserInterfaceServiceProvider.php
https://app.clickup.com/t/1vkzz0y
Required by https://github.com/ArkEcosystem/deployer.io/pull/1016
Adds layout content component to try to keep projects consistent with the layout and padding
-   [x] …
> refactor: layout content component

- resources/assets/js/tippy.js
- resources/views/inputs/upload-image-single.blade.php
https://app.clickup.com/t/237tdhe
Required for [this PR](https://github.com/ArkEcosystem/deployer.io/pull/1006)
For the component to be used in Deployer - we need to:
1. Add the ability to hide/show the text within the component. 
2. Show an optional tooltip
3. ~Allow HTML for the tooltip~
-   [ ] I added an explanation on how to use the component to the …
> refactor: upload image component changes

- resources/lang/en/pages.php
- src/Fortify/Components/UpdateProfileInformationForm.php
https://app.clickup.com/t/1vm01wa
This PR adds a toast message emit when profile information is updated.
To test, use this branch in deployer, go to settings and update the name or email address.
- …
> refactor: add toast message to profile update

- rector.php
https://app.clickup.com/t/23yuzw3
This PR skips Deployer's Livewire and View components from being evaluated by Rector to avoid breaking changes.
> refactor: add addition files to skip to rector config

- resources/views/pages/includes/layout-body.blade.php
- resources/views/pages/includes/layout-head.blade.php
- src/Providers/UserInterfaceServiceProvider.php
https://app.clickup.com/t/23ywkf6
Required by https://github.com/ArkEcosystem/deployer.io/pull/1030
> feat: layout head & body components

- examples/commonmark.md
- examples/fortify.md
- examples/ui.md
- resources/assets/css/_alerts.css
- resources/lang/en/alert.php
- resources/views/alert.blade.php
- resources/views/auth/login.blade.php
- resources/views/components/modals/2fa-recovery-codes.blade.php
- resources/views/livewire/flash-message.blade.php
- resources/views/profile/delete-user-form.blade.php
- src/Providers/UserInterfaceServiceProvider.php
- src/UserInterface/Components/FlashMessage.php
- src/UserInterface/Support/Enums/AlertType.php
- src/UserInterface/helpers.php
https://app.clickup.com/t/23yrye8
-   [x] Documentation _(if necessary)_
> refactor: update alert component as per new design

- resources/assets/css/_components.css
- resources/views/modal.blade.php
https://app.clickup.com/t/237t8um
This PR adjust the modal slightly to allow for matching design in deployer.
> refactor: make modal padding classes adjustable

- resources/lang/en/auth.php
https://app.clickup.com/t/2514c8t
> chore: update signup terms wording

- resources/assets/css/_cookie-consent.css
- resources/assets/css/_variables.css
- resources/lang/en/cookie-consent.php
- resources/views/pages/includes/cookie-banner.blade.php
- resources/views/pages/includes/layout-body.blade.php
- resources/views/pages/includes/layout-head.blade.php
- src/Providers/UserInterfaceServiceProvider.php
- src/Support/Facades/Visitor.php
- src/Support/Services/Visitor.php
https://app.clickup.com/t/24a7kxx
Required by https://github.com/ArkEcosystem/ark.io/pull/1037
> feat: add cookie banner & analytics

- resources/views/pages/contact.blade.php
https://app.clickup.com/t/1xjyet3
> refactor: added x-cloak to file upload element on contact page

- examples/ui.md
- resources/views/pages/includes/layout-body.blade.php
- usage/ui.md
https://app.clickup.com/t/1vz9365
Required by https://github.com/ArkEcosystem/ark.dev/pull/229
Breaking change to projects that already use the body component, since it will output the content again. I've done this to reduce the duplication across projects
-   [ ] …
> refactor: additional includes to body layout component

- resources/lang/en/urls.php
- resources/views/footer-social.blade.php
- resources/views/pages/contact.blade.php
- usage/ui.md
part of https://app.clickup.com/t/25xn3c7
> chore: remove reddit links

- resources/views/pages/includes/cookie-banner.blade.php
Will get further tweaks in https://github.com/ArkEcosystem/laravel-foundation/pull/277, but for now this setting will at least make the cookie in itself compliant with the rfc specs to avoid potential issues with other systems.
- …
> fix: make cookie consent cookie rfc compliant

- examples/ui.md
- resources/views/alert.blade.php
https://app.clickup.com/t/26mruaj
> refactor: alert title override

- resources/assets/css/_components.css
- resources/assets/css/_document.css
- resources/views/link-collection.blade.php
https://app.clickup.com/t/27h3tb5
> refactor: update link collection style

- resources/assets/css/themes/_deployer.css
- resources/assets/css/themes/_nodem.css
- usage/ui.md
https://app.clickup.com/t/27pwjqk
> chore: add deployer and nodem themes

- resources/views/link-collection.blade.php
This creates a smoother hover effect
> fix: add transition to link collection chevron

- resources/assets/css/_document.css
https://app.clickup.com/t/288097d
Required by https://github.com/ArkEcosystem/ark.dev/pull/247
> refactor: remove embed link image border

- resources/views/accordion.blade.php
When you pass a title to the accordion as a slot, it will always be rendered within the `span` element, granting us no control on that. This may cause issues when any block element is rendered within, or if we need to specify widths, etc.
Instead of adding additional config to accept classes for `span` element, I found it may be easier to just allow us to define any HTML we want for the title by making it a slot. In that case, we can just render the title as-is. For when it's passed as a prop, we can just leave it as a default span tag.
Quickly looking if this would make a breaking change to other projects:
- https://github.com/ArkEcosystem/nodem/search?q=x-ark-accordion (no accordions)
- https://github.com/ArkEcosystem/payvo.com/search?q=x-ark-accordion (no accordions)
- …
> refactor: fix how accordion's title is rendered when it's passed as a slot

- resources/assets/css/_document.css
- resources/views/separator.blade.php
- src/Providers/UserInterfaceServiceProvider.php
https://app.clickup.com/t/29ac91d
> feat: add separator component

- resources/assets/css/third-party/cookieconsent.css
- resources/assets/js/cookieconsent.js
- resources/views/pages/includes/cookie-banner.blade.php
Continuation of https://app.clickup.com/t/2705tvu
Copy of the package to have more sane-defaults and allowing us to avoid explicitly setting a domain for the cookie so it does not default to setting it for subdomains too.
Requires some further adjustments to the library still, draft until that's sorted
-   [ ] I added an explanation on how to use the …
> refactor: cookie consent adjustments

- resources/assets/js/cookieconsent.js
https://app.clickup.com/t/2705tvu
> refactor: disable cookie logging

- composer.lock
- config/tracking.php
- src/Providers/UserInterfaceServiceProvider.php
https://app.clickup.com/t/2acpffk
> chore: add cookie tracking config file

- README.md
- composer.json
- composer.lock
- src/CommonMark/View/FileViewFinder.php
- src/Documentation/DeriveGitCommitDate.php
- src/Documentation/Document.php
- src/Documentation/DocumentView.php
- src/Hermes/Models/DatabaseNotification.php
- src/Providers/MarkdownServiceProvider.php
- tests/CommonMark/Extensions/Highlighter/FencedCodeRendererTest.php
- tests/CommonMark/Extensions/Image/TwitterRendererTest.php
- tests/Fortify/Actions/AuthenticateUserTest.php
- tests/Fortify/Components/UpdateTimezoneFormTest.php
- tests/Fortify/Http/Requests/TwoFactorResetPasswordRequestTest.php
- tests/Fortify/Models/Concerns/HasLocalizedTimestampsTest.php
- tests/Fortify/Models/Concerns/HasPhotoTest.php
- tests/Support/TransformUrlsInvisiblyTest.php
- usage/documentation.md
Extracting this out of payvo and ark docs because it'll be needed in more places soon.
> feat: implement documentation discovery and parsing

- composer.json
- composer.lock
- rector.php
https://app.clickup.com/t/2acpfvk
Required by https://github.com/ArkEcosystem/template-laravel/pull/66
> chore: update rector & phpstan

- resources/assets/css/themes/_navy.css
> refactor: add navy color theme

- composer.json
- composer.lock
https://app.clickup.com/t/2acvr0a
Forked php-html-parser as it was no longer maintained: https://github.com/alexbarnsley/php-html-parser
> chore: update guzzlehttp/psr7

- resources/assets/js/cookieconsent.js
should have been `level`, not `levels` 
> fix: use "level" instead of "levels" for cookie consent check

- resources/views/pages/contact.blade.php
https://app.clickup.com/t/2t1pefv
> refactor: contact page cater no socials

- resources/assets/css/_document.css
- resources/lang/en/menus.php
- resources/tailwind.config.js
- resources/views/docs/sidebar-group.blade.php
- resources/views/pages/documentation.blade.php
- src/Documentation/DocumentWithCategory.php
- src/Providers/UserInterfaceServiceProvider.php
https://app.clickup.com/t/2bmyqdk
> refactor: move documentation page content

- resources/views/docs/share-links.blade.php
- resources/views/pages/documentation.blade.php
- src/Documentation/Document.php
- src/Documentation/DocumentWithCategory.php
https://app.clickup.com/t/26gt07j
Required by https://github.com/ArkEcosystem/ark.dev/pull/262
> refactor: handle foundation components & tutorials

- resources/assets/css/themes/_navy.css
- resources/views/navbar.blade.php
> fix: navy color palette and navbar borders

- resources/views/docs/sidebar-link.blade.php
- tests/Documentation/DocumentTest.php
https://app.clickup.com/t/27cggy3
> refactor: update docs sidebar link border size

- resources/lang/en/generic.php
- resources/views/no-results-basic.blade.php
- src/Providers/UserInterfaceServiceProvider.php
https://app.clickup.com/t/284b2xv
> feat: no results basic component

- resources/views/docs/sidebar-link.blade.php
https://app.clickup.com/t/284g3nu
> refactor: docs sidebar nested link remove arrow

- resources/views/docs/sidebar-group.blade.php
- src/Providers/DocumentationServiceProvider.php
- tests/Documentation/DocumentTest.php
- tests/Documentation/fixtures/index.blade.php
- tests/Documentation/fixtures/user-guides/getting-started/installation.md.blade.php
- tests/Documentation/fixtures/user-guides/transactions/how-to-vote-unvote.md.blade.php
https://app.clickup.com/t/289zr9z
> refactor: docs sidebar check group

- resources/assets/css/themes/_dark_blue.css
- resources/assets/css/themes/_dark_navy.css
https://app.clickup.com/t/28fdw9v
> chore: add dark blue theme

- resources/views/navbar.blade.php
- resources/views/navbar/hamburger.blade.php
- resources/views/navbar/items/desktop.blade.php
https://app.clickup.com/t/289zu9a
> refactor: allow navbar color overrides

- resources/views/social-link.blade.php
https://app.clickup.com/t/289zua9
> refactor: update footer social hover

- src/UserInterface/Http/Middlewares/DropInvalidLivewireRequests.php
- tests/UserInterface/Livewire/DropInvalidLivewireRequestsTest.php
- tests/UserInterface/Livewire/DummyComponent.php
https://app.clickup.com/t/28ff85q
> refactor: drop Livewire request that want to fire invalid events

- resources/views/chevron-toggle.blade.php
- resources/views/navbar/items/desktop.blade.php
- resources/views/navbar/items/dropdown-item.blade.php
https://app.clickup.com/t/289zu9n
> refactor: navbar dropdown updates

- resources/views/icon.blade.php
https://app.clickup.com/t/289zubc
> refactor: add icon component size

- resources/assets/css/themes/_dark_blue.css
- resources/tailwind.config.js
https://app.clickup.com/t/290qy9x
> refactor: allow dark blue colours

- resources/views/navbar/items/dropdown-item.blade.php
https://app.clickup.com/t/28nn9d3
> refactor: navbar dropdown hide external option

- resources/views/navbar/items/desktop.blade.php
- resources/views/navbar/items/dropdown-item.blade.php
https://app.clickup.com/t/28nnqj5
> refactor: close dropdown on link click

- resources/views/pages/includes/layout-body.blade.php
> refactor: allow for class overrides on the `body` element

- resources/tailwind.config.js
- resources/views/docs/sidebar-group.blade.php
- resources/views/docs/sidebar-link.blade.php
- tests/Documentation/DocumentTest.php
https://app.clickup.com/t/2d87t37
> refactor: update docs sidebar styling

- resources/assets/css/_simple_markdown.css
> fix: simple markdown links styling

- resources/views/docs/sidebar-group.blade.php
- resources/views/docs/sidebar-link.blade.php
- tests/Documentation/DocumentTest.php
https://app.clickup.com/t/28va9cp
> refactor: docs mobile sidebar design

- resources/views/navbar.blade.php
- resources/views/navbar/hamburger.blade.php
- resources/views/navbar/items/mobile.blade.php
- resources/views/sidebar-link.blade.php
https://app.clickup.com/t/28zxkj0
> refactor: update mobile navbar styling

- resources/assets/css/_general.css
- resources/views/footer-copyright.blade.php
- resources/views/footer-social.blade.php
- resources/views/footer.blade.php
https://app.clickup.com/t/2a30ha7
> refactor: footer & content spacing changes

- src/UserInterface/Http/Middlewares/DropInvalidLivewireRequests.php
- tests/UserInterface/Livewire/DropInvalidLivewireRequestsTest.php
https://app.clickup.com/t/29pmmrm
> fix: drop Livewire requests trying to call undefined methods

- usage/ui.md
> chore: update tippy usage ui readme

- resources/views/navbar/items/mobile.blade.php
needed for https://app.clickup.com/t/29qzfvb
> fix: close mobile menu when entry is clicked

- resources/assets/css/_components.css
- resources/assets/js/rich-select.js
- resources/lang/en/generic.php
- resources/views/inputs/rich-select.blade.php
- resources/views/simple-filter-dropdown.blade.php
- src/Providers/UserInterfaceServiceProvider.php
https://app.clickup.com/t/1v8gk1a
> refactor: simple filter component & rich-select popperjs

- resources/views/slider.blade.php
https://app.clickup.com/t/2b5hgkj
> refactor: slider force rows & columns to int

- resources/views/docs/sidebar-group.blade.php
- resources/views/docs/sidebar-link.blade.php
- tests/Documentation/DocumentTest.php
remainder of https://app.clickup.com/t/2c24em0
> fix: docs mobile menu tweaks

- resources/views/components/manage-notifications.blade.php
- resources/views/notification-icon.blade.php
https://app.clickup.com/t/2b01yfd & https://app.clickup.com/t/2b01xy3
> refactor: notification star filled when starred

- resources/views/docs/sidebar-link.blade.php
additional fix for https://app.clickup.com/t/2c24em0
> fix: docs sidebar nesting

- resources/assets/css/themes/_navy.css
- resources/tailwind.config.js
https://app.clickup.com/t/2aed25m
> refactor: add navy colour options

- resources/views/includes/slider/scripts.blade.php
Maybe fixes this: https://app.clickup.com/t/2aeeq5e
> fix: missing `type` on the `script` tag

- resources/views/pages/documentation.blade.php
https://app.clickup.com/t/2expj6y
> refactor: docs allow hiding edit link

- resources/assets/js/crop-image.js
- resources/views/inputs/upload-image-single.blade.php
- resources/views/js-modal.blade.php
Closes https://app.clickup.com/t/2ct30cf
The PR includes some refactoring for the lifecycle of the crop modal, the real fix for the issue is the promise that waits until the image has dimensions before initializing cropper
-   [ ] …
> fix: crop image modal issues

- README.md
- composer.json
- composer.lock
- src/Providers/TelescopeApplicationServiceProvider.php
- src/Providers/TelescopeServiceProvider.php
- usage/telescope.md
https://app.clickup.com/t/2gwf4p6
> feat: telescope service provider

- resources/lang/en/pages.php
https://app.clickup.com/t/2atvedn
Note: also updates the gdpr message to remove an extra `will`
> chore: update 2fa message to use app name

- resources/lang/en/generic.php
- src/UserInterface/helpers.php
https://app.clickup.com/t/2hdqdbm
> chore: add read time langs

- .github/workflows/compress.yml
- .svgo.js
- .svgo.yml
- src/Providers/UserInterfaceServiceProvider.php
- stubs/.github/workflows/compress.yml
https://app.clickup.com/t/2hdqdbm
Possible breaking change for any projects using the yaml file
> chore: update svgo file

- config/markdown.php
- src/Providers/CommonMarkServiceProvider.php
https://app.clickup.com/t/2hdqdbm
> refactor: markdown env use config file

- resources/assets/js/modal.js
- resources/views/external-link-confirm.blade.php
- resources/views/js-modal.blade.php
https://app.clickup.com/t/2gaj4zb
> refactor: external link modal tweaks

- resources/views/external-link-confirm.blade.php
- resources/views/js-modal.blade.php
https://app.clickup.com/t/2gaj4zb
> refactor: external link modal disable outside click

- resources/lang/en/cookie-consent.php
- resources/views/pages/includes/cookie-banner.blade.php
- resources/views/pages/includes/layout-body.blade.php
Needed for https://app.clickup.com/t/2jg8dyc
> refactor: allow overrides of contact URL in cookie modal

- resources/views/navbar.blade.php
Related to https://app.clickup.com/t/2hcp1w6
> refactor: add an option to remove the border on the navbar

- src/Documentation/Concerns/CanBeShared.php
for https://app.clickup.com/t/2hcxqt9
Facebook doesn't accept title
> refactor: add the ability to pass title in the sharing service

- resources/views/navbar.blade.php
- resources/views/navbar/items/mobile.blade.php
Dependant of https://github.com/ArdentHQ/msq.io/pull/134
related to https://app.clickup.com/t/2hcpgf3
> refactor: accept custom position class for mobile menu

- config/markdown.php
- src/CommonMark/Extensions/ExternalLink/ExternalLinkExtension.php
- src/CommonMark/Extensions/Link/LinkRenderer.php
- src/Providers/CommonMarkServiceProvider.php
- tests/CommonMark/Extensions/Link/LinkRendererTest.php
https://app.clickup.com/t/2kxu631
> refactor: add external link infix

- resources/assets/js/lazy-image-loading.js
https://app.clickup.com/t/2m3d41y
> feat: add lazy loading js

- src/Fortify/Components/TwoFactorAuthenticationForm.php
Related to https://app.clickup.com/t/2k72kdn
Dependant of https://github.com/ArdentHQ/msq.io/pull/193
> refactor: emit a public event when user enables/disables 2FA

- resources/assets/js/lazy-image-loading.js
https://app.clickup.com/t/2mmp1fy
> refactor: lazy loading adjustments

- resources/assets/js/lazy-image-loading.js
https://app.clickup.com/t/2kcxf3p
> fix: lazy loading image visible

- resources/views/navbar/items/desktop.blade.php
Needed for https://app.clickup.com/t/2k5y9y7
> refactor: allow left/right positioning of the dropdown in the navbar

- resources/lang/en/menu.php
- resources/views/navbar/hamburger.blade.php
https://app.clickup.com/t/2krf8rz
> refactor: navbar hamburger accessibility

- resources/assets/css/_document.css
https://app.clickup.com/t/2p833e9
> fix: center align article tweet

- resources/assets/css/_document.css
https://app.clickup.com/t/2pe131b
> refactor: add dark mode inline code styling

- .github/workflows/ci.yml
- phpunit.xml
- resources/views/components/blog/article-list.blade.php
- resources/views/components/blog/kiosk/create-article.blade.php
- resources/views/components/blog/search-input.blade.php
- resources/views/components/blog/sort.blade.php
- resources/views/pages/blog/kiosk/users/create.blade.php
- src/Blog/Models/User.php
- src/Fortify/Http/Middleware/EnforceTwoFactorAuthentication.php
- src/Providers/BlogServiceProvider.php
- tests/Blog/Feature/Http/Controllers/ArticleControllerTest.php
- tests/Blog/Feature/Http/Controllers/KioskControllerTest.php
- tests/Blog/Feature/Http/Controllers/UserControllerTest.php
- tests/Blog/Feature/Http/Livewire/ArticleListTest.php
- tests/Blog/Feature/Http/Livewire/Kiosk/CreateArticleTest.php
- tests/Blog/Feature/Http/Livewire/Kiosk/CreateUserTest.php
- tests/Blog/Feature/Http/Livewire/Kiosk/DeleteArticleTest.php
- tests/Blog/Feature/Http/Livewire/Kiosk/DeleteUserTest.php
- tests/Blog/Feature/Http/Livewire/Kiosk/UpdateArticleTest.php
- tests/Blog/Feature/Http/Livewire/Kiosk/UpdateUserTest.php
- tests/Blog/TestCase.php
- tests/Blog/Unit/Enums/CategoryTest.php
- tests/Blog/Unit/Models/ArticleTest.php
- tests/Blog/Unit/Models/UserTest.php
- tests/Blog/blade-views/layouts/app.blade.php
- tests/Blog/database/migrations/2022_04_25_081352_create_articles_table.php
- tests/Blog/database/migrations/2022_06_08_113820_add_soft_deletes_to_users_table.php
- tests/Blog/database/migrations/2022_07_25_122402_create_media_table.php
- tests/Pest.php
- tests/database/migrations/2014_10_12_000000_create_users_table.php
https://app.clickup.com/t/2er512f
> refactor: kiosk changes with tests

- resources/views/external-link.blade.php
https://app.clickup.com/t/2nh813u
> refactor: change external link icon to gray and reduce size

- src/CommonMark/Extensions/Link/LinkRenderer.php
follow up of https://app.clickup.com/t/2nh813u
> fix: apply link adjustments to commonmark

- resources/views/pages/includes/layout-head.blade.php
Adds the ability to change the meta viewport
Related to https://app.clickup.com/t/2typdka
Dependant of: https://github.com/ArdentHQ/msq.io/pull/302
> refactor: accept custom meta viewport

- resources/assets/css/_document.css
- src/CommonMark/Extensions/Image/TwitterRenderer.php
Closes https://app.clickup.com/t/2qg92rg
Notice that I'm using a custom CSS class instead of the tailwind one; the reason is to prevent that class from being removed with purgecss (its not a problem on msq but a potential problem)
- …
> refactor: center twitter embeds

- resources/views/components/blog/author-header.blade.php
Closes https://app.clickup.com/t/2qvh2ru (once released and updated on website)
> fix: incorrect article count text size

- resources/views/components/blog/article-list.blade.php
- resources/views/components/blog/search-input.blade.php
- resources/views/components/blog/sort.blade.php
Closes https://app.clickup.com/t/2qvh389
greys out the buttons and disables them if author has no articles
> refactor: disable search & sorting if no author articles

- resources/lang/en/pages.php
- resources/views/components/blog/article-list.blade.php
https://app.clickup.com/t/2qvh389
> refactor: update author no articles message

- resources/views/components/blog/filter-dropdown.blade.php
https://app.clickup.com/t/2p89rgh
> fix: mobile blog filter dropdown

- resources/views/components/blog/search-input.blade.php
https://app.clickup.com/t/2p89rgh
> fix: mobile blog search popup

- resources/assets/js/chart.js
- resources/views/scripts/dark-theme-script.blade.php
https://app.clickup.com/t/2nh828n
> refactor: chart allow auto theme mode

- resources/views/docs/sidebar-link.blade.php
- resources/views/docs/sidebar-subheading.blade.php
- tests/Documentation/DocumentTest.php
Kickback of https://app.clickup.com/t/2hyzd6y
Make sure to checkout and pair it with https://github.com/ArkEcosystem/docs/pull/251
How the docs look after foundation and docs changes:
-   [ ] Ready to …
> refactor: documentation sidebar border and padding fixes

- composer.json
- composer.lock
- src/Picasso/Avatar.php
- src/UserInterface/Support/Avatar.php
- tests/Documentation/DocumentTest.php
- tests/Fortify/Actions/CreateNewUserTest.php
- tests/Fortify/Components/ExportUserDataTest.php
- tests/Fortify/Responses/FailedTwoFactorLoginResponseTest.php
- tests/UserInterface/Livewire/DropInvalidLivewireRequestsTest.php
https://app.clickup.com/t/2nvx8nn
This PR primarily bumps Laravel's (`illuminate`) dependencies plus fixes all failing tests that failed due to breaking changes. The only third-party package that needed updates was `spatie/laravel-permission` because they dropped support for older Laravel versions, however active projects that use this package import it via their own `composer.json`.
- arkscic.com
- ark.io
- ark.dev
- landing pages
- ardenthq.com
- msq.io
- arkscan
-   [ …
> chore: bump Laravel deps

- resources/views/footer.blade.php
Needed for https://app.clickup.com/t/2tf7cud
Quick fix to solve the issue from screenshot below:
> fix: inline "an ARK product"

- .github/workflows/deps.yml
> chore: update deps workflow

- resources/views/errors/layout.blade.php
- resources/views/pages/includes/layout-body.blade.php
- resources/views/pages/includes/layout-content.blade.php
https://app.clickup.com/t/2ptfu0w
> refactor: centralise error page content

- resources/views/errors/layout.blade.php
- tests/UserInterface/Exceptions/HandlerTest.php
- usage/ui.md
https://app.clickup.com/t/2ptfu0w
> refactor: error page use contact route if exists

- resources/views/external-link.blade.php
- src/CommonMark/Extensions/Link/LinkRenderer.php
https://app.clickup.com/t/2r1juvk
> fix: external link icon alignment

- config/rules.php
- src/Rules/RegEx.php
- tests/Rules/RegExTest.php
https://app.clickup.com/t/2vtp3ec
> refactor: add youtube id regex

- .github/workflows/ci.yml
- .github/workflows/deps.yml
> chore: update nova credentials in workflows

- .github/workflows/format.yml
> fix: update workflows with correct nova secret

- resources/lang/en/pages.php
- resources/views/pages/contact.blade.php
Minor contact form adjustments to allow for more customization
> refactor: tweak contact form layout and props

- package.json
- yarn.lock
Closes https://app.clickup.com/t/3nh2tdy
This PR adds the required JS dependencies the foundation library uses on its components. This change does not affect the dependent projects but will solve the issues we have when we want to use a local version of the library, and we compile the assets (see screenshot).
1. In your local `laravel-foundation` branch run `yarn install` so it install the dependencies
2. Update the composer.json file of a project (msq probably). Example:
(Update path accordingly)
3. run `composer require arkecosystem/foundation` so it installs the local packages
4. Inside the project(let's say msq), run `yarn production` (or `yarn watch`). If your local branch of `laravel-foundation` is `main` it will fail. If you use this, should compile properly (don't forget the `yarn …
> refactor: add JS dependencies

- composer.json
- composer.lock
- rector.php
Updates the `LaravelSetList` references to make use of https://github.com/driftingly/rector-laravel as it has moved there as an extension
> fix: update LaravelSetList usage to match new package setup

- .github/workflows/ci.yml
- .github/workflows/compress.yml
- .github/workflows/deps.yml
- .github/workflows/format.yml
- config/fortify.php
- stubs/.github/workflows/ci.yml
- stubs/.github/workflows/compress.yml
- stubs/.github/workflows/deps.yml
- stubs/.github/workflows/format.yml
- stubs/.github/workflows/static.yml
https://app.clickup.com/t/867748abv
No breaking changes that apply to our workflows.
> chore: update workflow actions

- resources/views/components/truncate-dynamic.blade.php
- src/Providers/UserInterfaceServiceProvider.php
https://app.clickup.com/t/862j4wnqy
> feat: dynamic truncate component

- src/UserInterface/Components/ThrottledComponent.php
Handles diffs along with with days (24+ hours)
> refactor: use diff for remaining throttle seconds

- resources/views/inputs/checkbox.blade.php
- resources/views/inputs/includes/input-field.blade.php
- resources/views/inputs/input-with-icon.blade.php
- resources/views/inputs/input-with-prefix.blade.php
- resources/views/inputs/input-with-suffix.blade.php
- resources/views/inputs/input.blade.php
https://app.clickup.com/t/86779nrpt
> feat: add input debounce property

- resources/lang/en/generic.php
https://app.clickup.com/t/861mrubvf
> refactor: add pagination shorter lang

- resources/views/inputs/input-with-prefix.blade.php
- tests/UserInterface/Views/Inputs/InputWithPrefixTest.php
https://app.clickup.com/t/861mru5mf
Dependency of https://github.com/ArdentHQ/arkscan/pull/238
> refactor: output slot inside input-with-prefix component

- src/UserInterface/Support/QRCode.php
https://app.clickup.com/t/861mwhdz5
> refactor: allow qr code color overrides

- resources/assets/js/clipboard.js
- resources/views/clipboard.blade.php
https://app.clickup.com/t/861mwh3m9
required by https://github.com/ArdentHQ/arkscan/pull/283
> refactor: clipboard checkmarks option

- resources/assets/js/clipboard.js
required for https://app.clickup.com/t/862k0c1p4
> fix: handle clipboard checkmarks for both copy actions

- src/UserInterface/Http/Livewire/Concerns/HasPagination.php
https://app.clickup.com/t/861mxkyh7
required by https://github.com/ArdentHQ/arkscan/pull/319
draft to make sure it's worth the change
> refactor: allow disabling event on page change

- resources/assets/css/_general.css
- resources/assets/js/tippy.js
adds custom theme to tippy instances
> feat: set custom theme on tippy tooltip

- resources/views/inputs/checkbox.blade.php
https://app.clickup.com/t/861mxjtp5
required by https://github.com/ArdentHQ/arkscan/pull/360
> refactor: checkbox customisation

- resources/views/modal.blade.php
https://app.clickup.com/t/862k3539w
> refactor: modal option to disable overlay close

- resources/assets/icons/calendar-without-dots.svg
https://app.clickup.com/t/862k258az
> chore: add calendar without dots icon

- resources/views/clipboard.blade.php
https://app.clickup.com/t/861n1ff10
required by https://github.com/ArdentHQ/arkscan/pull/405
> refactor: allow clipboard component slot content

- resources/views/scripts/dark-theme-script.blade.php
https://app.clickup.com/t/861n2nngb
> refactor: don't trigger theme in maintenance mode

- resources/views/modal.blade.php
if no value was passed, it causes a js error due to invalid syntax (see screenshot)
> fix: cater for no modal disabling scroll width

- resources/views/external-link.blade.php
https://app.clickup.com/t/861n4ychg
> refactor: allow customising external link component icon

- resources/assets/js/chart.js
- resources/views/chart.blade.php
https://app.clickup.com/t/862kejxn0
required by https://github.com/ArdentHQ/arkscan/pull/564
> refactor: customisable chart tooltips

- resources/assets/js/chart.js
- resources/views/chart.blade.php
https://app.clickup.com/t/8678xkhgu
required by https://github.com/ArdentHQ/arkscan/pull/587
> refactor: allow chart labels as datetime objects

- resources/views/errors/layout.blade.php
https://app.clickup.com/t/862kfem4k
> refactor: error page metadata

- resources/views/inputs/select.blade.php
https://app.clickup.com/t/862kfqy81
> refactor: add select class property

- resources/assets/js/chart.js
- resources/views/chart.blade.php
https://app.clickup.com/t/862kg5cy1
> refactor: chart date unit override

- resources/assets/js/chart-theme.js
https://app.clickup.com/t/862kgby8k
required by https://github.com/ArdentHQ/arkscan/pull/692
> refactor: update dark mode axes color

- resources/assets/icons/ellipsis-vertical.svg
https://app.clickup.com/t/86drwqqf8
required by https://github.com/ArdentHQ/arkscan/pull/799
> chore: update vertical ellipsis icon

- examples/ui.md
- laravel-mix/markdownPlugin.js
- resources/views/pages/blog/article.blade.php
- resources/views/pages/includes/compress-image-scripts.blade.php
- resources/views/pages/includes/cookie-banner.blade.php
- resources/views/pages/includes/crop-image-scripts.blade.php
- resources/views/pages/includes/layout-body.blade.php
- resources/views/pages/includes/layout-head.blade.php
- resources/views/pages/includes/markdown-scripts.blade.php
- tests/Blog/TestCase.php
- usage/fortify.md
- usage/ui.md
https://app.clickup.com/t/86dt259z5
**Note: This introduces a breaking change**
> refactor: migrate webpack mix to vite

- resources/assets/css/_toasts.css
- resources/views/toast.blade.php
https://app.clickup.com/t/86dtacw4p
required by https://github.com/ArdentHQ/arkscan/pull/865
> refactor: toast component changes

- resources/assets/css/_toasts.css
- resources/views/livewire/toast.blade.php
- resources/views/toast.blade.php
https://app.clickup.com/t/86dtd79mc
required by https://github.com/ArdentHQ/arkscan/pull/869
> refactor: further toast component adjustments

- resources/vite.config.js
Related to https://app.clickup.com/t/86du9mnwd
Adds the base methods which are used in project vite configs
> chore: add base vite config

- resources/views/clipboard.blade.php
https://app.clickup.com/t/86dur5r5a
> refactor: clipboard component allow alpine property

- resources/assets/icons/cross-small.svg
https://app.clickup.com/t/86dv8cwjb
> chore: update cross small icon

- resources/views/inputs/includes/input-field.blade.php
Found as a result of https://app.clickup.com/t/86dwkehra
> refactor: make debounce input fields live

- src/UserInterface/Components/Concerns/HandleToast.php
Discovered when working on https://app.clickup.com/t/86dwkehra - the format for dispatching events has changed. This is also an issue on ARKScan - it can be confirmed when trying to submit a new wallet on `/compatible-wallets`
-   [ …
> fix: toast dispatch for updated livewire

- composer.json
- composer.lock
https://app.clickup.com/t/86dx44jx4
when i switched to larastan/larastan, I accidentally made it a dev dependency so it ends up not being installed on projects
> chore: move larastan dep to non dev
