ArkEcosystem/laravel-foundation

src/CommonMark/Extensions/Image/ContainerRenderer.php
src/CommonMark/Extensions/Image/ImageRenderer.php
src/CommonMark/Extensions/Image/YouTubeRenderer.php
src/CommonMark/Extensions/Link/LinkRenderer.php
src/Providers/CommonMarkServiceProvider.php

https://app.clickup.com/t/1ja2vuk
Dependant of https://github.com/ArkEcosystem/marketsquare.io/pull/2266
Updates the commonmark library to load the extensions again and adjust some extensions that has conflicts with this new version
- Merge this on [this PR](https://github.com/ArkEcosystem/marketsquare.io/pull/2266)
- Create some stuff with markdown, you can create a new article on nova for example (news accept most of the custom plugins since everything is whitelisted)
- Ensure the content is parsed as expected.
- Especially focus on custom plugins like embed tweets, youtube videos, links, etc
-   [x] I checked my (code) changes for obvious …

fix: update commonmark to handle extensions

---

src/CommonMark/View/FileViewFinder.php

The `CommonMarkServiceProvider` register a custom ViewFinder that is causing issues on my PR for updating the explorer dependencies and adding foundation (https://github.com/ArkEcosystem/explorer/pull/968)
Basically, it not loads the class-based components until I remove those lines
The custom class is used to handle views that contain a number like, for example (https://ark.dev/docs/core/releases/upgrade/2.4) the problem is that it was creating conflicts with the Number component that also returned a number 
-   [ ] I provided a screenshot of my …

fix: problem with custom view finder and numbers

---

src/CommonMark/Extensions/Link/LinkRenderer.php
tests/CommonMark/Extensions/Link/LinkRendererTest.php
tests/__snapshots__/LinkRendererTest__it_should_render_internal_links_with_(mailtotestark.io)__1.txt

Relates to https://app.clickup.com/t/u3re1w
-   [x] Tests _(if necessary)_

refactor: commonmark internal mailto link

---

src/CommonMark/Extensions/HeadingPermalink/HeadingPermalinkRenderer.php
src/Providers/CommonMarkServiceProvider.php

Dependant of: https://github.com/ArkEcosystem/ark.dev/pull/191
The old version of the `thephpleague/commonmark` library [used to add a `name` attribute](https://github.com/thephpleague/commonmark/blob/1.4/src/Extension/HeadingPermalink/HeadingPermalinkRenderer.php#L52) to the header permalinks (the links inside the `#`) since that name matches the link the internal links worked properly. (See anchor links on https://ark.dev/docs/glossary/glossary)
The current version, however, doesn't add that attribute meaning the links doest work. (See anchor links on ark.dev PR glossary section)
That name is necessary to make the anchor link works since the id have a `user-content-` prefix that doesn't match the link
This PR replaces the renderer for a new one that is exactly the same but adds the name …

fix: add `name` attribute to header permalink

---

src/UserInterface/Http/Middlewares/DropInvalidLivewireRequests.php
tests/UserInterface/Livewire/DropInvalidLivewireRequestsTest.php

If you manually register a component with `Livewire\Livewire::component('name', MyComponent::class)`, Livewire will not recognize that the component has been registered if you check with `app(LivewireManager::class)->getClass('name')`. However, if checking using the facade `Livewire\Livewire::getClass('name')` it will successfully find that component. Keep in mind that `Livewire\Livewire::class` is just a facade for `Livewire\LivewireManager::class`.
This has produced a bug where middleware to drop requests would fail even if the component is valid, only if the component has been manually registered (i.e. outside of default namespace).
Updated tests accordingly.
-   [ ] I checked my UI changes for any …

fix: Livewire not resolving any components during the middleware check for invalid requests

---

resources/assets/css/_document.css

https://app.clickup.com/t/pf94dc

refactor: document use default header sizes

---

resources/assets/css/_document.css

https://app.clickup.com/t/1kvru0z
Note: also updates permalink hover colour for all projects

refactor: use primary color for documentation header links

---

composer.json
composer.lock

This https://github.com/nunomaduro/larastan/commit/88422fb90e85385245fb1badcaf5fbd8e0a1530d hasn't been released but we need it to properly fix some errors.

chore: use `dev-master` for `larastan`

---

src/Fortify/Components/UpdatePasswordForm.php
tests/Fortify/Components/UpdatePasswordFormTest.php

https://app.clickup.com/t/1h29ba7
on msq go to `/account/settings/password` and try to update your password as described on the ticket, once the password is correct it should remove the validation error
-   [x] Tests _(if …

fix: reset password validation on typing

---

src/Providers/FoundationServiceProvider.php
src/Providers/StringMacroServiceProvider.php
src/Support/UrlInStringWrapper.php
tests/Support/UrlInStringWrapperTest.php

https://app.clickup.com/t/1pqfm7t
```
/*
* Some email clients will parse the content for urls, so they can convert them to a tags for convenience.
* Since some emails contain user entered data we have no control over these links, we don't like this because of
* security issues. With this Class we can check if parts of the string matches an url notation (with or without
* http(s)).
*
* Since adding an a tag will change the styling, you can optionally add one or more attributes to adapt the styling
* as an array where the index is the attribute and de value the value of the attribute.
*
* This class is available through a Str macro: \Str::wrapUrlsInBlankATag($string, $attributes);
*/
```
-   [ ] I …

feat: add UrlInStringWrapper string macro

---

phpstan.neon
src/Fortify/Components/Concerns/InteractsWithUser.php

https://app.clickup.com/t/1rgqjxw
This PR ignores the phpstan error "Constructor in ... has parameter ... with default value."

refactor: ignore phpstan error "Constructor in ... has parameter ... with default value"

---

phpstan.neon

https://app.clickup.com/t/1rp8ryp
As title said, this PR turns off the phpstan warning about [reporting unused ignores](https://phpstan.org/user-guide/ignoring-errors#reporting-unused-ignores).
-   [x] …

refactor: turn off phpstan warning about reporting unused ignores

---

.php-cs-fixer.php

The `phpdoc_to_comment` rule on the `.php-cs-fixer.php`  file is removing an `*` from some @var declarations which cause an error with phpstan where that declaration is used
You can see the problem in this commit: https://github.com/ArkEcosystem/marketsquare.io/pull/2387/commits/190d7394f1d76e1ffab07fd9c8c3227d3d05d223
After `php-cs-fixer` refactor the code phpstan complains about the issue that was meant to be solved
More info about the `phpdoc_to_comment ` rule here https://cs.symfony.com/doc/rules/phpdoc/phpdoc_to_comment.html
-   [ ] I provided a …

refactor: phpcs-fixer issues with @var declarations

---

phpstan.neon

https://app.clickup.com/t/1ty7d7t
This PR adds Explorer excluded paths to phpstan.neon

chore: add explorer excluded paths to phpstan.neon

---

resources/assets/css/_components.css

Change the border color in dark mode to match the marketsquare design.

fix: tile-selection-single border color in dark mode

---

resources/assets/js/crop-image.js
resources/views/inputs/upload-image-single.blade.php

https://app.clickup.com/t/1u9wyqy
This PR fixes an issue with crop image modal not removing the scroll lock when discarded.
1. merge this on MSQ
1. add new project
1. add platform/category and go to page 2
1. click on the image upload component
1. click `back` on the opened modal
1. expect to be able to scroll the page as usual
-   [ ] I added an explanation …

fix: remove scroll lock when closing crop modal

---

src/UserInterface/Support/Enums/FlashType.php

https://app.clickup.com/t/1mf3z8f
The FlashTypes are used to set the right type on the <x-ark-alert /> component.
The Enum delivers strings prefixed with `alert-`, but the <x-ark-alert /> component doesn't need this.
I've checked the usage in MSQ and this change should not cause compatibility with the current usage and will solve the bug.
-   [ ] I added an …

bug: alert styling and FlashTypes do not match

---

resources/views/inputs/upload-image-collection.blade.php

https://app.clickup.com/t/1mf0q5e
When the delete button is clicked while the image order is not yet completed after reordering, the deletion will result in deleting the wrong image or a `Trying to access array offset on value of type null` exception.
The simplest fix is to remove the delete button while the sorting is not yet finished. This will hardly or not at all be a visual change for the user since this will be just a fraction of a second and also only visible while hovering over an image.
I couldn't put the `wire:loading.remove="updateImageOrder"` on the button because of a known Livewire issue (https://github.com/livewire/livewire/issues/1012#issuecomment-687573922) with `wire:click` and `wire:loading` on the same element. I had to wrap the button in a `div` to make it work.
I …

fix: remove image collection delete button while loading

---

resources/views/external-link-confirm.blade.php
resources/views/inputs/upload-image-single.blade.php

https://app.clickup.com/t/1vx9hte
Since "js-modal" component now uses H2 for title, we don't need to implicitly add the header-2 class to style it.
- see https://github.com/ArkEcosystem/marketsquare.io/pull/2482#issue-792791200
- …

refactor: remove `header-2` title class from "js-modal" component

---

resources/views/external-link-confirm.blade.php
resources/views/inputs/upload-image-single.blade.php
resources/views/js-modal.blade.php

https://app.clickup.com/t/1vxangv
This PR fixes the margin between js-modal title and description to 16px.

fix: change title padding-bottom on "js-modal"

---

resources/views/external-link-confirm.blade.php
resources/views/inputs/upload-image-single.blade.php
resources/views/js-modal.blade.php

https://app.clickup.com/t/1w8man9
Fixes the vertical space (margin/padding) between title, description, image.. on js-modal and component that using js-modal, like external-link, crop image.
1. merge it on Marketsquare
1. open project and click on "website"
1. expects to see "external link" modal (https://www.figma.com/file/6VhdbE82NloQmxd6kJiGGN/MSQ?node-id=345%3A124979)
1. register new project, go to page 2
1. upload an image
1. expects to see "crop image" modal (https://www.figma.com/file/6VhdbE82NloQmxd6kJiGGN/MSQ?node-id=631%3A173889)
---
1. merge it on Payvo
1. open "view profile"
1. click on "qr-code" icon
1. expects to see "qr-code" modal (https://www.figma.com/file/89WPrtXdAWOvvmrpr2uypY/Payvo.com?node-id=271%3A16586)
-   [x] I checked my UI changes against the design and there …

fix: vertical space on "js-modal" component

---

resources/views/components/manage-notifications.blade.php

https://app.clickup.com/t/1n5x71q
Currently the notification dropdown for filtering all, read, unread etc. is trying to read from a non-existent lang file. This change fixes that by reading from ui:menus.notifications-dropdown...
- …

fix: notification filter dropdown using wrong lang file

---

src/Hermes/Models/DatabaseNotification.php

https://app.clickup.com/t/1x58xef
The bug is described in the Clickup Card. 
I couldn't find an easy way to write a test for it since there are no other Models present in foundation to make this work.
Since there are no existing tests for the `DatabaseNotification` in the test suite, I figured that is ok.
If needed, I can also create some test Models to be only used in the test suite to make it all testable. Let me know!
-   [ ] I regenerated the `icons.html` file and …

fix: create override to force use `action.url` in DatabaseNotification

---

resources/assets/css/_forms.css
resources/views/inputs/tags.blade.php

https://app.clickup.com/t/1wu12an
This PR adds dark mode support to the `taggle` class which is used on marketsquare project registration for adding tags to a project.
Corresponding MSQ PR for testing [here](https://github.com/ArkEcosystem/marketsquare.io/pull/2534).
- …

feat: add dark styles to tags

---

resources/views/auth/forgot-password.blade.php
resources/views/auth/reset-password.blade.php
resources/views/components/form-wrapper.blade.php

https://app.clickup.com/t/1n00ev8
This PR adjusts vertical form spacing on `forgot-password` and `reset-password` forms.
This change will be automatically applied on all projects that using this library.
- merge it on MSQ
- run `composer db:dev`
- open `/forgot-password`
- expects to see the correct vertical spacing (32px) https://www.figma.com/file/6VhdbE82NloQmxd6kJiGGN/MSQ?node-id=125%3A36792
- insert an email address `xxx@ark.io` and click "send reset link"
- open telescope `/telescope/mail`
- open the `SendPasswordResetNotification`
- click on the "reset password" inside the email
- expects to see the correct vertical spacing (32px)
- …

refactor: adjust vertical form spacing

---

resources/assets/css/_document.css

https://app.clickup.com/t/1wu10ff
Updates the markdown styling for dark mode
**Notes**
1. Notice that [the design](https://www.figma.com/file/6VhdbE82NloQmxd6kJiGGN/MSQ?node-id=4175%3A279847) doesn't have all the elements on the markdown (like tables, hr separators, etc so I tried to follow the style we have generally
2. The image caption is different from the design but that is in purpose (asked Oleg)
3. I am not updating the image placeholder but created a ticket for that instead https://app.clickup.com/t/1truvpa
To test: try to create an article with all the markdown components you can think (headers, links, images, etc) of and ensure they looks good in dark mode
-   [x] I checked my UI changes for …

refactor: dark mode for blog article (markdown styling)

---

resources/assets/css/_forms.css

https://app.clickup.com/t/1wu12fh
Adjusts the form inputs with icons used on the registration form:
To test: merge on msq, recompile, compare design

refactor: register form dark mode inputs

---

resources/views/inputs/password-toggle.blade.php

https://app.clickup.com/t/1xb4882
Didnt find a design for this but I assume is just using a darker blue:

refactor: password toggle use darker blue on dark mode

---

resources/tailwind.config.js
resources/views/navbar/items/desktop.blade.php
resources/views/navbar/items/mobile.blade.php

https://app.clickup.com/t/1u471fb
- adds shadow based on figma (there wasn't an already existing shadow setup based on what was in the designs)
- adds scrolling to mobile (e.g. for when the dropdown is open and too tall for the device)
-   [ ] Documentation _(if …

refactor: add navbar dropdown shadow

---

resources/assets/css/_document.css

Slight tweak to apply the proper gray-500 text to the article bodies

fix: article text dark mode styling

---

resources/views/inputs/tile-selection.blade.php

https://app.clickup.com/t/1p846jt
This PR add dark mode support for the tile-selection 'show more' button. Noticed when registering a project on MSQ.
To test with MSQ, require this branch, run yarn prod, and start to register a new project with a browser window of <640. …

refactor: dark mode for 'show more' button on tile selection

---

resources/assets/css/_forms.css

https://app.clickup.com/t/1wu12bf
As part of [this](https://github.com/ArkEcosystem/marketsquare.io/pull/2563) MSQ PR, this adds a couple of dark mode styles to the `disabled-tags-input` class.
-   [ ] …

refactor: add dark mode for disabled tags

---

resources/assets/css/_components.css

https://app.clickup.com/t/1p87gj9
tile-link-icon was changing color immediately on hover - this add a transition inline with the background change

fix: add transition to tile link icon

---

resources/views/js-modal.blade.php
resources/views/modal.blade.php

Dependant of https://github.com/ArkEcosystem/marketsquare.io/pull/2530
Related to: https://app.clickup.com/t/1qa4wyq
The modal now adds the name so it can be used as selector on dusk tests
-   [ ] …

refactor: accept custom name selector on modals

---

resources/views/auth/two-factor-challenge.blade.php

https://app.clickup.com/t/1tfab68
This change replaces the custom header used in `two-factor-challenge.blade.php` with the `component-heading.blade.php` component which is used in signup and signin.
- …

refactor: use same header component for 2fa page as login and register

---

resources/views/navbar-notifications.blade.php
resources/views/notification-icon.blade.php

https://app.clickup.com/t/1za52r5
- Now the whole notification item is clickable (to make sense with the design that have a hover color) which means:
- The "take me there" text and the icon doesn't have links anymore
- The icon used to use the `->route`  method for the link and the "take me there" a `->link` method, now it uses the `->link` method as default and fallbacks to the `->route`
To test add this PR to msq
-   [ ] I regenerated the `icons.html` file and checked …

refactor: notification icon design adjustments

---

resources/assets/css/_components.css
resources/views/components/manage-notifications.blade.php

https://app.clickup.com/t/1tmzztg
Adjust the checkbox color from success-500 to success-600. I *think* I got them all.
Note this also add a pointer cursor to the tile selection checkbox which was missing previously (you can test by selecting platforms when creating a project in MSQ).
-   [ ] I added an explanation on how to use the component to the readme …

fix: adjust checkbox color

---

resources/views/inputs/password-toggle.blade.php

https://app.clickup.com/t/1xb4882
According to the feedback the icon is now gray with a hover color on dark mode
https://user-images.githubusercontent.com/17262776/148412859-a17cc2c2-da6e-4137-9d01-8e0ebec52acc.mov
**To test:** merge in msq, recompile assets go to login form
-   [ ] I added an explanation on how to use the component to the readme _(if …

refactor: adjust reveal password icon color in dark mode

---

resources/views/dropdown.blade.php

related to Sam feedback here https://app.clickup.com/t/1xwbkk7
Adds the `buttonClassContracted` option in the dropdown to add classes that are only used when the dropdown is closed
Dependant of: 
-   [ …

refactor: dropdown closed button class

---

resources/assets/js/compress-image.js
resources/views/inputs/upload-image-collection.blade.php

https://app.clickup.com/t/21zxnhy
The new version of compressorjs has some odd functionality which means if we pass in a minWidth and maxWidth, it will try to resize the image to one of them. This is causing issues for image uploads in MSQ.
~~The solution here is to get the natual width/height of an image and pass those values into compressorjs.~~
The *new* solution here is to just set the width/height to `undefined` if they are not passed in. compressorjs seems to be like that.
-   [ ] I provided a screenshot of my changes to the component _(if …

fix: compress image size

---

src/Fortify/Components/TwoFactorAuthenticationForm.php

https://app.clickup.com/t/1y8m9ag
This PR adds a custom message to the required validation when entering an OTP. 
To test, require this branch on MSQ, go to setting and try to enable 2fa without entering a code in, you should see a custom tooltip error.
-   [ ] …

fix: OTP required validation message

---

resources/views/profile/two-factor-authentication-form.blade.php

https://app.clickup.com/t/22wjvpy
To test, go to account/settings in MSQ. resize browser to mobile so the 2fa verification code is underneath the QR code, and check border color.
-   [x] Ready to be …

fix: dark mode border color in 2fa mobile view

---

resources/views/pagination-url.blade.php

https://app.clickup.com/t/1ve57ru
The PR adds the missing chevron left and right icons to the `pagination-url.blade.php` component.
Note I also noticed a flash of the search form on page load so added `x-cloak` to that.
This can be tested in deployer by seeding the db and going to a tokens activity page. The seed does not create enough activity items to trigger the pagination so I temporarily set it to a small number in `TokenActivityController.php` (`->paginate(2)`)
Required for [this PR](https://github.com/ArkEcosystem/deployer.io/pull/1003)
-   [ ] …

fix: pagination-url icons

---

resources/assets/js/chart.js

https://app.clickup.com/t/23t2m9q
The plugin try to access the axes in the `options.scales.{}` object with `xAxes` and `yAxes` but in the script they are defined with `x` and `y`.
Changing their names to `xAxes` and `yAxes` solve the issue.
-   [ ] Documentation _(if …

refactor: fix axes name on chart.js script

---

resources/lang/en/pages.php

https://app.clickup.com/t/237texy
The deployer support page design has a lowercase 't' in 'team'.

fix: use lowercase t for team on contact page

---

resources/views/auth/register-form.blade.php
src/Fortify/Components/RegisterForm.php

https://app.clickup.com/t/23ypqp6
This PR makes changes to the registration form used for registering an account. Previously we have `name` and `username`, we only use both on MSQ which uses custom components anyway. I have removed `username` as a required parameter since deployer uses only `name` in the db (but calls it username in the UI - see [here](https://github.com/ArkEcosystem/deployer.io/pull/1040) for solution to that).
Also included is a fix to the password rules in the UI.
-   [ ] I provided a screenshot of my changes to the component _(if …

refactor: have registration default to name and fix password input

---

resources/views/external-link-confirm.blade.php

https://app.clickup.com/t/1z0m205
The issue was due to the polling of the `Alert` component. Because of the Livewire hook for this to work, `initExternalLinkConfirm();` will be executed every 2 seconds. Because of that the (confirmed) link in the modal will also get a `data-external-link-confirm="true"` again.
Solved by adding `data-safe-external="true"` to the link in the modal.
-   [ ] I regenerated the `icons.html` file and checked if my newly added icon is shown …

fix: external link unclickable if request processed after open

---

resources/views/dropdown.blade.php

https://app.clickup.com/t/21w7ru4
Required by https://github.com/ArkEcosystem/nodem/pull/382

refactor: allow dropdown zindex override

---

resources/views/link-collection.blade.php

Reduces padding for the link collection to be like the middle option here

refactor: reduce link collection padding

---

resources/assets/js/cookieconsent.js

https://app.clickup.com/t/2pbubxb
Make cookies work with the old `levels` property by adjusting them if they were found. This ensures that existing viewers will not run into issues if they had the old cookie type set on their machine
-   [ ] Documentation _(if …

refactor: make cookies backwards compatible

---

src/Documentation/Document.php

Sometimes images can slip into the discovery if they are stored in the same directory as the actual docs.

fix: prevent images from being treated as pages

---

resources/views/pages/contact.blade.php
src/Documentation/Document.php

For example on https://docs.payvo.com/docs/wallet/support/security there is no neighbour following the security page but because of how the lookup works it picks up the https://docs.payvo.com/docs/wallet/profiles/contacts page because that does exist locally.

fix: check for exact matches by slug

---

src/Documentation/Document.php

It's possible to get a model instance that is empty so we need to check that the array representation isn't because the model itself will evaluate to not being empty but the array will evaluate to being empty.

fix: ensure the document model has properties

---

src/Documentation/Document.php

Other documentations can use model as-is except that 2 private methods need to be overwritten. Means a bit of duplication but saves more than it causes.

refactor: mark `private` document methods as `protected`

---

src/Documentation/DocumentWithCategory.php

> Depends on https://github.com/ArkEcosystem/laravel-foundation/pull/308
This is an optional model that can be used by documentations that host multiple products based on categories, like https://ark.dev and https://docs.payvo.com do.

feat: add document model with category support

---

resources/assets/css/themes/_navy.css
resources/views/navbar.blade.php
resources/views/pages/includes/layout-head.blade.php

This PR allows you to add the `favicons` slot to the component and manually specify all the favicon stuff. Good use case would be overriding which public directory the favicons are loaded from.
This PR also changes navy 500 color which is only used in a border between navbar and hero, to be consistent with red color (Slack).
-   [ ] I added an explanation on …

refactor: allow favicon data to be passed as slot

---

resources/views/navbar/hamburger.blade.php

https://app.clickup.com/t/27cgg69 (needs another PR for the project's repo when foundation merged)
Separator left/right padding between button and the hamburger menu:
- 24px on each side
- 32px on md screen, as per design
Hamburger menu hover state:
- 12px horizontal padding
- 20px horizontal padding on md screen
-   [ ] I added an explanation on how to use …

refactor: hamburger menu & mobile separator paddings

---

resources/views/navbar/hamburger.blade.php

https://github.com/ArkEcosystem/laravel-foundation/pull/319 accidentally reverted the hamburger padding. This reverts that revert

fix: navbar hamburger padding

---

resources/assets/js/read-more.js
resources/views/read-more.blade.php

https://app.clickup.com/t/29b9vta
For one, `$el` in Alpine v3 no longer retrieves the root element, but the current element. Second, we need to truncate on init, but only on next tick once elements are in the DOM. Same thing with resizing, on resize we want to wait a tick for all elements to update, and only then **truncate** and not **truncate and hide option**.
-   [ ] I regenerated the `icons.html` file and checked if my newly added icon is shown correctly _(if …

fix: read-more button not showing up

---

resources/views/includes/slider/scripts.blade.php
resources/views/slider.blade.php

Part of https://app.clickup.com/t/2aeeq5e
Adds the ability to not have all slides of equal height: https://swiperjs.com/swiper-api#param-autoHeight

refactor: add the ability to pass `autoHeight` option to slider

---

resources/views/pages/documentation.blade.php

part of https://app.clickup.com/t/2c24em0

fix: set docs sidebar width to avoid shrinking

---

resources/views/components/manage-notifications.blade.php
src/Hermes/Components/ManageNotifications.php

This will allow for HTML notifications on the notifications page in addition to the navbar

fix: allow html notifications in overview

---

resources/assets/css/_components.css

https://app.clickup.com/t/2expj1v
Fixes a regression to the sidebar link css in #356

fix: re-add sidebar css regression

---

resources/views/notification-icon.blade.php

https://app.clickup.com/t/2ecaefh
Allows overriding the relatable for notifications, so it can be passed in withTrashed

refactor: allow relatable notification icon

---

resources/views/inputs/checkbox.blade.php

This PR adds the ability to defer updating of the Livewire state bound by the checkbox.
Needed for https://app.clickup.com/t/2fu8bnw

refactor: allowed deferred checkbox data binding

---

resources/assets/js/markdown-editor/markdown-editor.js
resources/assets/js/markdown-editor/plugins/underline.js
resources/assets/js/markdown-editor/utils/utils.js

https://app.clickup.com/t/2ff3c10 & https://app.clickup.com/t/2ff34z6
- Underline is fixed by targeting proper editor element to focus
- Embed modals is fixed by wrapping the MDEditor property into `Alpine.raw()` as this was some weird issue because Alpine properties are proxies
- Quick Link fix -- opening a link modal and clicking "Ok" would not add link due to missing handler
-   [ ] I regenerated the `icons.html` file and checked if my newly added icon is shown …

fix: markdown editor's underline and embed modals

---

src/Providers/NovaServiceProvider.php

It seems that the library we use for managing permissions (https://github.com/vyuldashev/nova-permission) hasn't been updated to support Nova v4. So we can use Nova v4 in other projects, this PR temporarily disables these tools from registering within Nova.
I'd personally go for building in-house tool for this, but we can do that later on when we need to CRUD permissions and roles.
-   [ ] I regenerated the `icons.html` file and checked if my newly added icon is shown …

fix: disable permission tool from registering in Nova v4

---

resources/views/pages/includes/layout-head.blade.php

Meta titles can have chars like `&` that are not parsed on the title that the users see on browser, this PR ensures we do not escape titles like we do [with the rest of the metadata](https://github.com/ArkEcosystem/laravel-foundation/blob/main/resources/views/metadata-tags.blade.php)
Related to https://app.clickup.com/t/2hdq5gc
-   [ ] I added an explanation …

refactor: do not escape meta title

---

resources/views/navbar.blade.php

Related to https://app.clickup.com/t/2hcpgf3
Note: In case you are wondering this PR does not affect to arkio, ardenthq, arkscan, arklauncher or marketsquare (actually fixes an invisible issue since the spacer used to be a little shorter than it should)
You can test it by using the devtools to repalce the class `<div class="mb-0.5 h-20"></div>` with `<div class="h-21"></div>` on all the sites that depends on this library and checking that everything looks good
-   [ ] I …

refactor: add parameter to adjust navbar height

---

resources/views/auth/two-factor-challenge.blade.php
resources/views/components/component-heading.blade.php

needed for https://app.clickup.com/t/2hcxxvc
This PR uses the databag for 2FA verification page. That approach allows us to override the `component-heading` with our own component, just like we did to add colorful banner. Since now we use databag, we can't just rely on the fact that all other products have databag variables to 2FA pages implemented, so I just added a quick check for variables for pages to not fail when loaded.
-   [ ] I regenerated the `icons.html` file …

refactor: use databag for 2fa pages

---

resources/assets/js/modal.js
resources/views/external-link-confirm.blade.php

Adds a way to inject custom scripts to the confirmation modal (used to add history handling for this ticket https://app.clickup.com/t/2hxy2vm)
And a new method in the modal used for the same purpose.
Dependant of https://github.com/ArdentHQ/msq.io/pull/196
-   [X] I checked my UI changes for any responsiveness issues
-   [x] I regenerated the `icons.html` file and checked if my newly added icon is shown correctly _(if necessary)_
-   [ ] …

refactor: accept custom scripts on confirm modal and on init method

---

resources/views/auth/login.blade.php

Dependant of https://github.com/ArdentHQ/msq.io/pull/230
The login form is currently pointing to the `login` route which really is the route for showing the login form (not the one for submitting). That route usually matches the POST route but causes issues if we ever override that route (like in the dependant PR)
So... This PR updates the login submit URL to point directly to the controller action for login submission.
-   [ ] I regenerated the `icons.html` file and …

refactor: submit to controller action

---

resources/views/external-link-confirm.blade.php

Changes the color of the overlay for dark mode in the external link modal
Dependant of https://github.com/ArdentHQ/msq.io/pull/256

feat: dark mode modal overlay color for external links

---

resources/views/external-link-confirm.blade.php

Updates the default text color for dark mode

refactor: external link modal dark text color

---

config/fortify.php

https://app.clickup.com/t/2jfwnbm
Turns out, if response cache is enabled, authentication pages don't show any validation errors. To test, add the 
`DoNotCacheResponse::class` middleware to `middleware` in fortify config file, just like in this PR. Foundation already imports `spatie/laravel-responsecache` so we can reference that class in foundation itself.
Since other projects have their `fortify.php` config file exported, this will need to be updated in all of them so keep an eye on PRs for those projects.
-   [ ] I provided a screenshot of my …

fix: do not cache response for Fortify's authentication pages

---

resources/views/docs/edit-page.blade.php

fix: center "edit page" on mobile for documentation pages

---

resources/views/extended-footer.blade.php

Allow overriding extended footer background, for https://github.com/ArkEcosystem/arkscic.com/pull/56

fix: allow extended footer color overrides

---

resources/views/alert.blade.php
resources/views/components/blog/article-content.blade.php
resources/views/components/blog/related-articles.blade.php
resources/views/inputs/markdown.blade.php
resources/views/navbar.blade.php
resources/views/pagination-url.blade.php
resources/views/pagination.blade.php
resources/views/profile/delete-user-form.blade.php

https://app.clickup.com/t/1mjqkr9
While I still believe `{{ trans() }}` is a better choice due to consistency because we're forced to use `trans` in other places (component props, e.g. `<x-ark-component :prop="trans('something')" />`), most of the Blade files use `@lang` so it makes sense to change it to be consistent.
-   [ ] I added an explanation on how to …

refactor: standardize translations in Blade files

---

src/UserInterface/Exceptions/Concerns/OverridesExceptionView.php
src/UserInterface/Exceptions/Handler.php
tests/Stubs/ExceptionHandler.php
tests/TestCase.php
tests/UserInterface/Exceptions/HandlerTest.php
tests/blade-views/layouts/app.blade.php

https://app.clickup.com/t/2ptfu0w
Used to show 500 error page if an error we don't handle is thrown

refactor: handle error codes outside templates

---

resources/views/inputs/rich-select.blade.php

Doesn't necessarily fix https://app.clickup.com/t/2uhduet, but it's the same issue.
https://tailwindcss.com/docs/min-width

fix: change `min-w-max-content` to `min-w-max` for rich select component

---

resources/views/navbar.blade.php

slight adjustment to the active state of the mobile navbar entries

fix: mobile navbar active state

---

composer.lock
rector.php

https://app.clickup.com/t/867732vfz

refactor: update rector dependency and configuration

---

resources/lang/en/general.php
src/UserInterface/Components/ThrottledComponent.php

https://app.clickup.com/t/86778pwhn
Moved ThrottledComponent to foundation. Also tweaked to output minutes when hours are used. E.g. "2 hours, 59 minutes", "2 hours, 1 minute", etc
-   [ ] Ready to be …

feat: add throttled component

---

resources/views/inputs/toggle.blade.php

https://app.clickup.com/t/863gpm9q9
There is always a bg (depending on whether there's a value or not), so the white background is unnecessary

fix: remove unnecesary toggle bg

---

resources/views/inputs/includes/input-prefix-icon.blade.php
resources/views/inputs/input-with-prefix.blade.php

Needed to allow for a smaller icon on ARKScan

refactor: allow passing input prefix icon size

---

resources/views/inputs/input-with-prefix.blade.php

sets proper defaults to avoid all icons changing to `sm` for input prefixes

fix: set default prefix icon size

---

resources/views/dropdown.blade.php

https://app.clickup.com/t/861mru5mf

refactor: allow dropdown component without button

---

resources/assets/css/_tables.css

https://app.clickup.com/t/861mwnpqg
Potentially a breaking change - the last cell when responsive shouldn't have any right padding. This wasn't the case

fix: last table cell padding

---

resources/assets/js/tippy.js

Add a html version for tippy tooltips with `data-tippy-html-content`

feat: allow html version of tippy tooltip

---

resources/assets/js/modal.js
resources/views/modal.blade.php

https://app.clickup.com/t/863h8wx7b
Allows for disabling the page scroll lock above a set width

refactor: modal allow disabling scroll lock at page width

---

resources/assets/css/_components.css
resources/views/js-modal.blade.php

https://app.clickup.com/t/863h8wx7b
improves some customisation to the js modal, and also updates some styling (e.g. the close button)

refactor: update js modal customisation & design

---

resources/views/js-modal.blade.php

https://app.clickup.com/t/863h8wx7b
The failover init causes issues with accessing $refs.modal if the Modal instance is instantiated higher up in a parent. This caused an error in devtools. 
Potentially a breaking change if anything still relied on the basic init
-   [ ] …

refactor: remove basic init from js modal

---

resources/assets/js/navbar.js

https://app.clickup.com/t/862k7ffck

refactor: handle multiple navbar instances

---

resources/assets/js/chart-theme.js
resources/assets/js/chart.js
resources/views/chart.blade.php

https://app.clickup.com/t/862kebkg6
required by https://github.com/ArdentHQ/arkscan/pull/561
There doesn't seem to be any usage of the chart component / CustomChart JS outside of explorer. I tried to modify in a way that wouldn't cause breaking changes
-   [ ] …

refactor: chart component updates

---

resources/assets/js/tippy.js

https://app.clickup.com/t/86dqm6nmv
Fixes an issue where tooltips using `data-tippy-content` don't update the tooltip content/value so changing the fiat on explorer results in using the old tooltip value
Required by https://github.com/ArdentHQ/arkscan/pull/703
-   [ ] …

refactor: use attribute content when applying tippy

---

resources/views/dropdown.blade.php

Originally needed for https://app.clickup.com/t/86dt0dttt but got missed
Was required in https://github.com/ArdentHQ/arkscan/pull/848

refactor: allow dropdown content class override

---

phpstan.neon

As a result of https://app.clickup.com/t/86dtc3dmu
It's possible to include a phpstan config file from within another. See [here](https://github.com/ArdentHQ/arkscan/pull/863/commits/bb822f1ed37c5bbfc25eaea0d87f8488ac6e792d#diff-0361f0c81f363476ddc6f44ab36fcbe66ee685d5f4c2a46b054924591544b766)
-   [ ] I added an explanation on how to use the component to the …

chore: remove explorer specific phpstan config

---

resources/tailwind.config.js

https://app.clickup.com/t/86dwgnvth
With the recent updates to Node v20 and v22, `module.exports` doesn't work. I believe because it's because imports are treated as ESM by default.
This changes the tailwind config to `export default` instead
-   [ ] Documentation _(if …

refactor: tailwind export
